### ISSUE TITLE
Can we implement this to working system?

### ISSUE THREAD

**Issue by acseckin** [br3ttb/Arduino-PID-AutoTune-Library#15]
Can we implement this to working system? I want to add this to find constants of quadrotor control.

**Comment by vickylance** [comment]
Same here I cant get the right PID values for my quadcopter and its not yet flying. I also want to know if this can find the right PID values for a quadcopter to fly stable. Or atleast a detailed tutorial on how this library works like the detailed tutorial on the Arduino PID library would be very useful.
