### ISSUE TITLE
Kp both for PonE and PonM?

### ISSUE THREAD

**Issue by edgsc** [br3ttb/Arduino-PID-AutoTune-Library#16]
I have a doubt that others may have too. The PID library got an update for choosing Kp applied on actual error (Proportional on Error, PonE) or Kp applied on deltaInput (Proportional on Measurement).
Does the Autotune PID library calculated Kp is useful for both or only PonE? Thanks!

**Comment by br3ttb** [comment]
The z-n method was designed for PonE (PonM didn't exist,) but should still give you stable numbers.
