### ISSUE TITLE
Simulated input equation - Where does it come from?

### ISSUE THREAD

**Issue by edgsc** [br3ttb/Arduino-PID-AutoTune-Library#17]
Hello, from where does the simulated input equation comes from?

input = (kpmodel / taup) *(theta[0]-outputStart) + input*(1-1/taup) + ((float)random(-10,10))/100;

What kind of dynamics? How was it linearized?

Thanks!!!

**Comment by br3ttb** [comment]
By "linearized" I assume you mean "discretized," as the model is already
linear.

The model is a standard first order with dead time:
taup*dydt+y=kpmodel*output(t-theta)

To discretize, replace dydt with (y- lasty)/deltaT and use algebra to
simplify.  For the code I assumed deltaT was constant and equal to 1
