### ISSUE TITLE
peak-to-peak amplitude for relay is 2*oStep

### ISSUE THREAD

**Issue by t0mpr1c3** [br3ttb/Arduino-PID-AutoTune-Library#2]
In the formula for the ultimate gain Ku, oStep is used as the measure of amplitude for the relay which is half the peak-to-peak amplitude. The amplitude of the induced oscillation is measured by ( absMax - absMin ) i.e. the peak-to-peak amplitude. This would appear to underestimate Ku by a factor of 2.

**Comment by br3ttb** [comment]
yeah at first glance it looks like I messed up.  I'll need to take a closed look, but it seems that the library is yielding more conservative tunings than it should.
