### ISSUE TITLE
use sampleTime from PID 

### ISSUE THREAD

**Issue by t0mpr1c3** [br3ttb/Arduino-PID-AutoTune-Library#3]
Wouldn't it make sense to have sampleTime in the auto tuner as some multiple (>=1) of the sampleTime used in the PID.

**Comment by br3ttb** [comment]
I had thought to do this originally, but that would require passing a reference to a PID object.  I kind of like the idea that this  Library is a completely separate entity, more easily modded to fit the needs of others.

**Comment by t0mpr1c3** [comment]
That figures, it is more flexible that way. I had envisaged attributes of the PID class being inherited by the Auto Tuner.
